# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PolyMaGui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PolyMaGui(object):
    def setupUi(self, PolyMa):
        PolyMa.setObjectName("PolyMa")
        PolyMa.resize(1154, 707)
        self.centralwidget = QtWidgets.QWidget(PolyMa)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1141, 691))
        self.label.setStyleSheet("font: 75 8pt \"MS Shell Dlg 2\";")
        self.label.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("122.gif"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 620, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("font: 14pt \"Tw Cen MT Condensed Extra Bold\";\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))qradialgradient(spread:pad, cx:0.551, cy:0.642045, radius:1.097, fx:0.295, fy:0.301136, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(255, 0, 0);")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 620, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("font: 14pt \"Tw Cen MT Condensed Extra Bold\";\n"
"border-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255))qradialgradient(spread:pad, cx:0.551, cy:0.642045, radius:1.097, fx:0.295, fy:0.301136, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"color: rgb(255, 0, 0);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 0, 411, 161))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("125.gif"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(470, 260, 201, 161))
        self.label_3.setStyleSheet("background:transparant;\n"
"border-radius:none;\n"
"")
        self.label_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3.setLineWidth(0)
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("127.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(860, 480, 231, 61))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("129.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(860, 570, 231, 61))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("129.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(930, 0, 171, 151))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap("130.gif"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        PolyMa.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(PolyMa)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1154, 21))
        self.menubar.setObjectName("menubar")
        PolyMa.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(PolyMa)
        self.statusbar.setObjectName("statusbar")
        PolyMa.setStatusBar(self.statusbar)

        self.retranslateUi(PolyMa)
        QtCore.QMetaObject.connectSlotsByName(PolyMa)

    def retranslateUi(self, PolyMa):
        _translate = QtCore.QCoreApplication.translate
        PolyMa.setWindowTitle(_translate("PolyMa", "MainWindow"))
        self.pushButton.setText(_translate("PolyMa", "ACTIVATE"))
        self.pushButton_2.setText(_translate("PolyMa", "EXIT"))


if __name__ == '__main__':
    import sys
    app=QtWidgets.QApplication(sys.argv)
    PolyMaGui = QtWidgets.QMainWindow()
    ui = Ui_PolyMaGui()
    ui.setupUi(PolyMaGui)
    PolyMaGui.show()
    sys.exit(app.exec_())